In [1]:
import pandas as pd

# 병합/분할

In [2]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ['홍길동', '신사임당', '이순신', '논개']
})
df2 = pd.DataFrame({
    "ID": [1, 2, 3, 5],
    "Score": [85, 90, 78, 92]
})
display(df1)
display(df2)

   ID  Name
0   1   홍길동
1   2  신사임당
2   3   이순신
3   4    논개

   ID  Score
0   1     85
1   2     90
2   3     78
3   5     92

## 행병합
- merge: column기반 병합 (sql join과 유사)
- join: index기반 병합
- concat

### merge
- merge: column기반 병합

In [3]:
# inner : 두 df에 공통된 행만 병합
pd.merge(df1, df2, on="ID", how="inner")

   ID  Name  Score
0   1   홍길동     85
1   2  신사임당     90
2   3   이순신     78

In [4]:
# left outer : 왼쪽 df의 모든 행 + 오른쪽 df에 공통된 행만 병합
pd.merge(df1, df2, on="ID", how="left")

   ID  Name  Score
0   1   홍길동   85.0
1   2  신사임당   90.0
2   3   이순신   78.0
3   4    논개    NaN

In [5]:
# right outer : 오른쪽 df의 모든 행 + 왼쪽 df에 공통된 행만 병합
pd.merge(df1, df2, on="ID", how="right")

   ID  Name  Score
0   1   홍길동     85
1   2  신사임당     90
2   3   이순신     78
3   5   NaN     92

In [6]:
# outer : 오른쪽 df의 모든 행 + 왼쪽 df에 모든 행 병합
pd.merge(df1, df2, on="ID", how="outer")

   ID  Name  Score
0   1   홍길동   85.0
1   2  신사임당   90.0
2   3   이순신   78.0
3   4    논개    NaN
4   5   NaN   92.0

In [7]:
customer_df = pd.DataFrame({
    'customer_id': [100, 200, 300],
    'name': ['홍길동', '신사임당', '윤봉길']
}).set_index('customer_id') # 일반컬럼을 index로 변환
display(customer_df)

order_df = pd.DataFrame({
    'customer_id': [100, 500],
    'order_id': ['o1', 'o2']
}).set_index('customer_id')
display(order_df)

             name
customer_id
100           홍길동
200          신사임당
300           윤봉길

            order_id
customer_id
100               o1
500               o2

### join
- join: index기반 병합

In [8]:
# left join (기본값)
customer_df.join(order_df, how="left")

             name order_id
customer_id
100           홍길동       o1
200          신사임당      NaN
300           윤봉길      NaN

In [9]:
# right join (기본값)
customer_df.join(order_df, how="right")

            name order_id
customer_id
100          홍길동       o1
500          NaN       o2

In [10]:
# inner join (기본값)
customer_df.join(order_df, how="inner")

            name order_id
customer_id
100          홍길동       o1

In [11]:
# outer join (기본값)
customer_df.join(order_df, how="outer")

             name order_id
customer_id
100           홍길동       o1
200          신사임당      NaN
300           윤봉길      NaN
500           NaN       o2

In [12]:
# customer_df # customer_id가 인덱스로 지정된 상태
# customer_df.reset_index() # 0-based index 다시 사용 가능
customer_df.reset_index(drop=True)

   name
0   홍길동
1  신사임당
2   윤봉길

### concat
axix=0 일때, sql union과 유사하게 세로방향 병합이 가능하다.
(동일한 구조의 df을 연결할때 유용하다.)

In [16]:
member_df1 = pd.DataFrame({
    'Name': ['홍길동', '이순신'],
    'Age': [33, 48]
})
member_df2 = pd.DataFrame({
    'Name': ['신사임당', '논개'],
    'Age': [27, 55]
})

display(member_df1)
display(member_df2)

  Name  Age
0  홍길동   33
1  이순신   48

   Name  Age
0  신사임당   27
1    논개   55

In [15]:
# 행고정 df연결 병합

# .reset_index(drop=True): index를 0부터 다시 매기기
member_df = pd.concat([member_df1, member_df2], axis=0).reset_index(drop=True)
member_df

   Name  Age
0   홍길동   33
1   이순신   48
2  신사임당   27
3    논개   55

In [17]:
member_df = pd.concat([member_df1, member_df2], axis=1)
member_df

  Name  Age  Name  Age
0  홍길동   33  신사임당   27
1  이순신   48    논개   55

In [20]:
# 고객 주문 정보 조회
# - 아래 df을 병합해서 고객/주문/상품 정보를 하나의 df에서 조회
# - 1. customers:orders 1:n
# - 2. order:order_details 1:n
# - 3. order_details:products 1:1

# 고객 정보 데이터프레임
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'customer_name': ['Alice', 'Bob', 'Charlie', 'David']
})

# 주문 정보 데이터프레임
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 2, 4],
    'order_date': ['2024-08-01', '2024-08-02', '2024-08-03', '2024-08-04']
})

# 제품 정보 데이터프레임
products = pd.DataFrame({
    'pid': [201, 202, 203],
    'product_name': ['Widget', 'Gadget', 'Thingamajig']
})

# 주문 내역 데이터프레임
order_details = pd.DataFrame({
    'order_id': [101, 101, 102, 103, 104],
    'product_id': [201, 203, 202, 201, 203],
    'quantity': [2, 1, 5, 2, 3]
})

In [21]:
df = pd.merge(customers, orders, on='customer_id', how='left')
df = pd.merge(df, order_details, on='order_id', how='left')
df = pd.merge(df, products, left_on='product_id', right_on='pid', how='left')
df

,customer_id,customer_name,order_id,order_date,product_id,quantity,pid,product_name
0,1,Alice,101.0,2024-08-01,201.0,2.0,201.0,Widget
1,1,Alice,101.0,2024-08-01,203.0,1.0,203.0,Thingamajig
2,2,Bob,102.0,2024-08-02,202.0,5.0,202.0,Gadget
3,2,Bob,103.0,2024-08-03,201.0,2.0,201.0,Widget
4,3,Charlie,NaN,NaN,NaN,NaN,NaN,NaN
5,4,David,104.0,2024-08-04,203.0,3.0,203.0,Thingamajig

## 열병합

In [22]:
# melt()
# - id_vars 식별컬럼(기준컬럼)
# - value_vars 병합하고자하는 컬럼명
# - var_name 병합된 컬럼명
# - value_name 값 컬럼명

score_df = pd.DataFrame({
    "Name": ["홍길동", "신사임당", "이순신"],
    "Math": [85, 90, 78],
    "English": [88, 85, 90],
    "Science": [92, 87, 85]
})
score_df

   Name  Math  English  Science
0   홍길동    85       88       92
1  신사임당    90       85       87
2   이순신    78       90       85

In [24]:
pd.melt(
    score_df,
    id_vars=['Name'],
    value_vars=['Math', 'English', 'Science'],
    var_name='Subject',
    value_name='Score'
).sort_values('Name').reset_index(drop=True)

   Name  Subject  Score
0  신사임당     Math     90
1  신사임당  English     85
2  신사임당  Science     87
3   이순신     Math     78
4   이순신  English     90
5   이순신  Science     85
6   홍길동     Math     85
7   홍길동  English     88
8   홍길동  Science     92

## 분할

In [25]:
# qcut() 분위 분할
num_df = pd.DataFrame({
    "value": [10,20,30,40,50,60,70,80,90,100]
})
num_df

   value
0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100

In [26]:
num_df['qcut_bin'] = pd.qcut(
    num_df['value'],
    q = 4, # q == 분위 수
    labels = ['Q1', 'Q2', 'Q3', 'Q4'] # 분위를 표시할 이름
)

num_df

   value qcut_bin
0     10       Q1
1     20       Q1
2     30       Q1
3     40       Q2
4     50       Q2
5     60       Q3
6     70       Q3
7     80       Q4
8     90       Q4
9    100       Q4